-- One-off maintenance script, already run — the test-account cleanup this
-- performed is done. Kept only because it can't be deleted from this
-- environment; nothing to run here anymore. Do not re-run: it deletes every
-- auth account except williamaarfing@gmail.com and would wipe any real
-- accounts added since.
