-- One-off diagnostic script used to debug the "duplicate Almus" question,
-- already resolved (there was only ever one Almus — the fix was in
-- src/lib/org.js's listOrgs()). Kept only because it can't be deleted from
-- this environment; nothing to run here anymore.
