-- One-off cleanup script written on the mistaken assumption there were two
-- separate "Almus" organizations. There was only ever one — the real fix
-- was in src/lib/org.js's listOrgs() not scoping to the current user. This
-- script was never actually run (its own safety check refused to proceed).
-- Kept only because it can't be deleted from this environment; nothing to
-- run here.
